spring.config.import=spring-freemarker.properties

spring.main.lazy-initialization = true
server.compression.enabled = true

spring.web.resources.cache.period=365d
spring.web.resources.chain.strategy.content.enabled = true


#---
spring.config.activate.on-profile=development

#spring.web.resources.cache.period=
spring.web.resources.chain.cache = false
spring.web.resources.static-locations = \
  classpath:/META-INF/resources/, classpath:/resources/, file:src/main/resources/static/, classpath:/public/
