spring.freemarker.settings.incompatible_improvements=2.3.33
spring.freemarker.settings.default_encoding=UTF-8
spring.freemarker.settings.log_template_exceptions=false
spring.freemarker.settings.wrap_unchecked_exceptions=true
spring.freemarker.settings.fallback_on_null_loop_variable=false
spring.freemarker.settings.sql_date_and_time_time_zone=JVM default
spring.freemarker.settings.object_wrapper=com.example.demo.config.freemarker.DeferableObjectWrapper( \
    ${spring.freemarker.settings.incompatible_improvements}, \
    forceLegacyNonListCollections=false, iterableSupport=true, simpleMapWrapper=true, \
    defaultDateType=freemarker.template.TemplateDateModel.DATETIME )


ERROR_HTML_ELEMENT_ID=html_error_fallback
MY_ERROR_PAGE=/error/500.html

spring.freemarker.settings.template_exception_handler=\
    com.example.demo.config.freemarker.HtmlStreamTemplateExceptionHandlers$MetaRefreshRethrowHandler( \
        "${MY_ERROR_PAGE}", "${ERROR_HTML_ELEMENT_ID}" )


#---
spring.config.activate.on-profile=development

spring.freemarker.settings.cache_storage=freemarker.cache.NullCacheStorage
spring.freemarker.template-loader-path=file:src/main/resources/templates/

spring.freemarker.settings.template_exception_handler=\
    com.example.demo.config.freemarker.HtmlStreamTemplateExceptionHandlers$JsEnhancedHtmlDebugHandler( \
        "${ERROR_HTML_ELEMENT_ID}" )
